name: Python CI  # Name of the workflow

on:
  push:
    branches: [ main ]       # Triggers workflow on push to main
  pull_request:
    branches: [ main ]       # Triggers workflow on PR to main

jobs:
  build:
    runs-on: ubuntu-latest   # Run this job on a virtual machine with Ubuntu

    steps:
    # Step 1: Checkout your code from GitHub repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # You can use other versions like 3.10, etc.

    # Step 3: Install Flake8 (Python linter)
    - name: Install Flake8
      run: pip install flake8

    # Step 4: Run linting on your code
    - name: Lint code
      run: flake8 . --max-line-length=120
      # This checks all Python files for syntax/style issues

    # Step 5: Log in to Docker Hub using your GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Build the Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-ci-app .

    # Step 7: Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-ci-app